### ISSUE TITLE
Xamarin.Forms.Xaml.XamlParseException

### ISSUE THREAD

**Issue by halukmy** [mfractor/xamarin-forms.swipe-view#1] opened 2020-07-16 07:48 UTC
![image](https://user-images.githubusercontent.com/2916333/87642213-dfd86280-c751-11ea-96c6-eac024f8aca1.png)

why do you think this problem goes on?

**Comment by matthewrdev** [comment] 2020-07-16 11:45
@halukmy Most likely due to using a version of Xamarin.Forms that does not support linear items layout.

Where are you seeing this issue? In a personal app or from this project? If this project, have you made any changes to it? (out of the box, the solution is working fine for myself).

**Comment by halukmy** [comment] 2020-07-16 18:51
can you mail me with bin files ( actually with downloaded libs)

**Comment by matthewrdev** [comment] 2020-08-26 02:07
@halukmy My day work picked up and this fell by the wayside.

Can you clarify "mail me the bin files"? Running and experimenting with this sample can be done by cloning the repo, running a nuget restore and then debugging the codebase. There are no additional binary files required.

I'm closing this issue as significantly more information is needed. Please reply back and we can work to figure out what the issue is.

**Closed by matthewrdev** 2020-08-26 02:07 UTC
